wanamubackend:
  restart: always
  build: .
  ports:
    - 3001:3001
  environment:
    - WU_DB_NAME=wanamu
    - WU_DB_USER
    - WU_DB_PASSWORD
    - WU_DB_DATA
    - WU_DB_HOST
    - WU_HTTP_AUTH
    - WU_HTTP_USER
    - WU_HTTP_PASSWORD
    - WU_ENV
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
    - ${$WU_DB_DUMP}:/var/lib/postgresql/dump
