'use strict';
/**
 * Created by Christian on 5/2/2015.
 */
var assert = require('assert'),
    ListingController = require('../../../dist/server/server/controller/Listing'),
    sinon = require('sinon');

describe('Test Listing Controller', function () {
    var lc;

    beforeEach(function(){
        lc =  ListingController;
    });

    it('Should have a function named get,list, create, delete and updated', function () {
        assert.equal(typeof lc, 'object');
        assert.equal(typeof lc.list, 'function');
        assert.equal(typeof lc.get, 'function');
        assert.equal(typeof lc.create, 'function');
        assert.equal(typeof lc.delete, 'function');
        assert.equal(typeof lc.update, 'function');
    });

    it('Creates Listings', function (done) {
        var req,
            res,
            testTitle ='Test controller Listing create' ;
        req = res = {};
        req.body = {
            title: testTitle
        };
        res.send = sinon.spy();
        res.status = sinon.stub().returns(res);
        //We assume there is a user with id 1 generated by the test setup
        req.session = {
            user: {
                id: 1
            }
        };
        lc.create(req, res).then(function(){
            assert(res.send.called, true, 'Response.send not called');
            assert(typeof res.send.callCount, 1, 'Response.send was called more or less then once');
            assert(typeof res.send.args[0][0], 'object');
            assert(res.send.args[0][0].title, testTitle);
            assert(res.send.args[0][0].userId, 1);
            done();
        });

    });
});
